/* NEED TO SORT FOREIGN KEYS */

DROP DATABASE IF EXISTS FDB;
CREATE DATABASE FDB;
USE FDB;

DROP TABLE IF EXISTS Club;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Manager;
DROP TABLE IF EXISTS Stadium;
DROP TABLE IF EXISTS Trophies;
DROP TABLE IF EXISTS Fixtures;
DROP TABLE IF EXISTS News;

CREATE TABLE Club(
  CLUBID INT(4) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CLUBNAME VARCHAR(20) NOT NULL,
  MANAGER VARCHAR(50),
  STADIUM VARCHAR(20) NOT NULL,
  CLUBPOSITION INT(2)
);

CREATE TABLE Player(
  PLAYERID INT(4) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CLUBID INT(4),
  FNAME VARCHAR(20) NOT NULL,
  LNAME VARCHAR(20) NOT NULL,
  SQUADNO INT(2),
  PLAYERPOSITION VARCHAR(20),
  HEIGHT VARCHAR(6),
  PREFFOOT CHAR(1),
  DOB DATE,
  CLUBAPPS INT(3),
  SEASONAPPS INT(2),
  NATIONALITY VARCHAR(20),
  CLUBGOALS INT(3),
  SEASONGOALS INT(3),
  CLEANSHEETS INT(3)
);

CREATE TABLE Manager(
  MANAGERID INT(4) AUTO_INCREMENT PRIMARY KEY,
  CLUBID,
  FNAME VARCHAR(20),
  LNAME VARCHAR(20),
  DOB DATE,
  JOINEDCLUB DATE,
  NATIONALITY VARCHAR(20)
);

CREATE TABLE Stadium(
  NAME VARCHAR(20),
  CLUBID,
  ADDRESS VARCHAR(100),
  POSTCODE VARCHAR(6),
  CAPACITY INT(6),
  DATEBUILT DATE
);

CREATE TABLE Trophies(
  COMPETITION VARCHAR(20) NOT NULL,
  YEAR INT(4),
  CLUBNAME VARCHAR(20) NOT NULL
);

CREATE TABLE Fixtures(
  MATCHID INT(8) PRIMARY KEY NOT NULL,
  MATCHDATE DATE,
  HOMETEAM VARCHAR(20),
  AWAYTEAM VARCHAR(20),
  HOMETEAMSCORE INT(2),
  AWAYTEAMSCORE INT(2)
);

CREATE TABLE News(
  NEWSID INT(4) PRIMARY KEY,
  CLUBNAME VARCHAR(20),
  TITLE VARCHAR(50) NOT NULL,
  CONTENT VARCHAR(2000) NOT NULL
);
