DROP DATABASE IF EXISTS FDB;
CREATE DATABASE FDB;
USE FDB;

DROP TABLE IF EXISTS Club;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Manager;
DROP TABLE IF EXISTS Stadium;
DROP TABLE IF EXISTS Trophies;
DROP TABLE IF EXISTS Fixtures;
DROP TABLE IF EXISTS News;

CREATE TABLE Club(
  CLUBID INT(2) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CLUBNAME VARCHAR(20) NOT NULL,
  STADIUM VARCHAR(20) NOT NULL,
  CURRENTPOSITION INT(2)
);

CREATE TABLE Position_History(
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY (CLUBID)
    REFERENCES Club(CLUBID),
  COMPETITION VARCHAR(20) NOT NULL,
  YEAR INT(4) NOT NULL,
  POSITION INT(2)
);

CREATE TABLE Player(
  PLAYERID INT(4) AUTO_INCREMENT PRIMARY KEY,
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY (CLUBID)
    REFERENCES Club(CLUBID),
  FNAME VARCHAR(20) NOT NULL,
  LNAME VARCHAR(20) NOT NULL,
  SQUADNO INT(2) NOT NULL,
  PLAYERPOSITION VARCHAR(20),
  HEIGHT VARCHAR(6),
  PREFFOOT CHAR(1),
  DOB DATE,
  CLUBAPPS INT(3),
  SEASONAPPS INT(2),
  NATIONALITY VARCHAR(20),
  CLUBGOALS INT(3),
  SEASONGOALS INT(3),
  SEASONASSISTS INT(3),
  CLEANSHEETS INT(3)
);

CREATE TABLE Manager(
  MANAGERID INT(4) AUTO_INCREMENT PRIMARY KEY,
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY (CLUBID)
    REFERENCES Club(CLUBID),
  FNAME VARCHAR(20) NOT NULL,
  LNAME VARCHAR(20) NOT NULL,
  DOB DATE,
  JOINEDCLUB DATE,
  NATIONALITY VARCHAR(20)
);

CREATE TABLE Stadium(
  NAME VARCHAR(20) NOT NULL,
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY(CLUBID)
    REFERENCES Club(CLUBID),
  ADDRESS VARCHAR(100) NOT NULL,
  POSTCODE VARCHAR(10) NOT NULL,
  CAPACITY INT(6),
  DATEBUILT DATE
);

CREATE TABLE Trophy(
  COMPETITION VARCHAR(20) NOT NULL,
  YEAR INT(4) NOT NULL,
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY(CLUBID)
    REFERENCES Club(CLUBID)
);

CREATE TABLE Fixture(
  MATCHID INT(8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  MATCHDATE DATE,
  HOMETEAM VARCHAR(20) NOT NULL,
  AWAYTEAM VARCHAR(20) NOT NULL,
  HOMETEAMSCORE INT(2),
  AWAYTEAMSCORE INT(2)
);

CREATE TABLE News(
  NEWSID INT(4) AUTO_INCREMENT PRIMARY KEY,
  CLUBID INT(2) NOT NULL,
    FOREIGN KEY (CLUBID)
    REFERENCES Club(CLUBID),
  TITLE VARCHAR(50) NOT NULL,
  CONTENT VARCHAR(2000) NOT NULL,
  AUTHOR VARCHAR(40)
);
